### ISSUE TITLE
No report appearing

### ISSUE THREAD

**Issue by KDMcCracken** [okld/streamlit-pandas-profiling#10]
Started using this component again after a short hiatus and it seems to be having issues generating a report. The spinner "Generating profile report..." appears and then nothing. It just seems to disappear with no errors or report generated.

**Comment by knorthover** [comment]
Getting the same behavior on a new installation. I've tried this with Streamlit v0.72 and 0.73.1.

**Comment by okld** [comment]
Issue should be fixed now.

**Comment by knorthover** [comment]
Great, works well.  Thank you
