### ISSUE TITLE
RuntimeError: Data of size 1160.4MB exceeds write limit of 50.0MB

### ISSUE THREAD

**Issue by nlpsbr** [okld/streamlit-pandas-profiling#11]
![Screenshot 2021-04-07 at 6 42 10 PM](https://user-images.githubusercontent.com/77673324/113871881-f9827400-97d0-11eb-9407-1bb58b11a52b.png)

**Comment by okld** [comment]
This issue was reported in #3 

> Your error seems related to this streamlit issue: streamlit/streamlit#1983 (comment)
> As said in the link above, some approaches exist in the following thread: streamlit/streamlit#400 (comment)
