### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by chiehpower** [okld/streamlit-pandas-profiling#25]
Hi,

Thanks for your contribution to this feature!

Is there any chance to add a feature to export the pdf file for this report?

Thank you!

BR,
Chieh

**Comment by okld** [comment]
Hello @chiehpower,

Unfortunately PDF exports are not supported by pandas profiling. FYI this feature was also requested there https://github.com/pandas-profiling/pandas-profiling/issues/235:

> There are multiple interactive options in the html report, for example, when clicking on toggle details a new menu appears for that variable. I am afraid that functionality is not available in a pdf. I agree that a stylish pdf would be nice, but it would be quite hard to put in there all the information that the html currently holds. If it was a simple html, there are multiple tools to convert an html to pdf in Python, but I am afraid it would be more challenging without extra preparation.

**Comment by chiehpower** [comment]
I see!! Thanks for your information!!
