### ISSUE TITLE
How to get around the Runtime Error?

### ISSUE THREAD

**Issue by vnguyendc** [okld/streamlit-pandas-profiling#3]
How do I get around the RunTime error set by streamlit?

![image](https://user-images.githubusercontent.com/53052652/94175788-2be80780-fe65-11ea-8a38-4bed06832da2.png)

**Comment by Ghasel** [comment]
Hello @vnguyendc 

Your error seems related to this streamlit issue: https://github.com/streamlit/streamlit/issues/1983#issuecomment-690912846
As said in the link above, some approaches exist in the following thread: https://github.com/streamlit/streamlit/issues/400#issuecomment-648580840
