### ISSUE TITLE
Support for Caching

### ISSUE THREAD

**Issue by AVCarreiro** [okld/streamlit-pandas-profiling#5]
Hello, thank you for this very useful streamlit component!

Are there any plans (because it seems it isn't supported right now) to be able to cache the executed reports? 

HTMLContainer from pandas-profiling is not hashable out-of-the-box, and I can't seem to think of an easy hash function (please let me know if you do), and st_profile_report cannot run inside the @st.cache() decorated function, otherwise we don't get the reports as it doesn't run.

Thank you, 

André Carreiro

**Comment by okld** [comment]
Hello @AVCarreiro,

The streamlit pandas profiling is just a viewer for ProfileReport objects. Running st_profile_report() won't save you computation time. What you want to cache though is the profile report generation.

Here's how you could do it:

```python
@st.cache(allow_output_mutation=True)
def generate_report(df):
    return ProfileReport(df, explorative=True)

st_profile_report(generate_report())
```

The magic resides in that `allow_output_mutation=True`. This tells Streamlit not to hash that ProfileReport object.

**Comment by okld** [comment]
Hello @AVCarreiro,

`streamlit-pandas-profiling` is just a viewer for ProfileReport objects. Caching `st_profile_report()` won't save you computation time. What you want to cache though is the profile report generation.

Here's how you could do it:

```python
df = pd.read_csv("path/to/csv/data")

@st.cache(allow_output_mutation=True)
def generate_report(df):
    return ProfileReport(df, explorative=True)

st_profile_report(generate_report(df))
```

The magic resides in that `allow_output_mutation=True`. This tells Streamlit not to hash that ProfileReport object.

**Comment by AVCarreiro** [comment]
Thank you, I had tried caching only the profile report but without the magic of allow_output_mutation. It works 👍
