### ISSUE TITLE
Support for new layout features

### ISSUE THREAD

**Issue by KDMcCracken** [okld/streamlit-pandas-profiling#6]
Thanks for your work on this. Any plans to add compatibilty with StreamLit's new layout features? Specifically the ability to add horizontal st.beta_columns(). It would be really cool to have the analysis of these columns stack horizontally to reduce page length.

Discussed here:
https://discuss.streamlit.io/t/new-layout-options-for-streamlit/6148

**Comment by okld** [comment]
Hello @KDMcCracken,

What you could do is generate multiple profile reports, one with correlations, one with missing values, etc., and use my component to display each report in different columns using streamlit layouts.

**Comment by okld** [comment]
Closing this issue for now. Feel free to re-open it if you find the feature missing despite using [profile report's settings](https://pandas-profiling.github.io/pandas-profiling/docs/master/rtd/pages/advanced_usage.html).
