### ISSUE TITLE
Feature request: scrolling

### ISSUE THREAD

**Issue by minhlong94** [okld/streamlit-pandas-profiling#7]
To use Pandas Profiling with Streamlit, we need to convert it to HTML using `.to_html()` method, which may be lengthy. However, your repo does not support scrolling enable yet, so I want to request it to enable scrolling, like in `st.components.v1.components.html(... , scrolling = True)`.

**Comment by okld** [comment]
New release add a new `height` parameter. If you set a height, you'll automatically have a scrollable report.
